apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: e2e-tests-go-jmixmrej
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/e2e-tests-go-jmixmrej:caaf185b6e3ffdc769b5873c374ded2ef2f9b9ea
        name: container-image  
